FROM python:3.10-slim

WORKDIR /app

COPY app.py /app/
COPY model.keras /app/

RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install --no-cache-dir tensorflow==2.18.0 flask pillow numpy gunicorn==21.2.0 matplotlib requests

EXPOSE 5003

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5003", "app:app"]
